import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./store-provider";

const ubuntu = Ubuntu({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={ubuntu.className}>{children}</body>
      </html>
    </StoreProvider>
  );
}
